name: cb_file_manager
description: A new Flutter application.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <=3.32.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^9.1.0
  provider: ^6.1.2
  path_provider: ^2.1.1
  package_info_plus: ^4.1.0
  equatable: ^2.0.7
  permission_handler: ^12.0.0+1
  video_player: ^2.8.1
  # video_thumbnail: ^0.5.3  # Commented out the pub.dev version
  # Sử dụng video_thumbnail trực tiếp từ GitHub repository
  video_thumbnail:
    git:
      url: https://github.com/EduardoM-GO/video_thumbnail
      ref: master # Có thể thay đổi ref để chỉ định branch hoặc tag cụ thể
  path: ^1.8.3
  shared_preferences: ^2.2.2
  window_manager: ^0.4.3 # Added for desktop window management
  remixicon: ^1.4.1 # Remix Icons package
  visibility_detector: ^0.4.0+2 # Added for detecting visible thumbnails
  diacritic: ^0.1.6 # Vietnamese text normalization
  # FTP connection - using custom implementation

  # ObjectBox database dependencies
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0

  # Media Kit packages for cross-platform video playback (including Windows)
  media_kit: ^1.1.11 # Primary package
  media_kit_video: ^1.2.5 # Video widget
  media_kit_native_event_loop: ^1.0.9 # Support for platforms
  media_kit_libs_windows_video: ^1.0.11 # Windows video support
  media_kit_libs_android_video: ^1.3.7 # Android video support
  # media_kit_libs_ios_video: ^1.1.4 # Uncomment if you need iOS support
  # Pin to 7.4.3: 7.4.4 has a Pigeon channel name mismatch that breaks Android initialization
  # (PlatformException(channel-error, Unable to establish connection on channel.)).
  flutter_vlc_player: 7.4.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  file_picker: ^10.1.2
  win32: ^5.0.9
  crypto: ^3.0.6
  # Dependency injection
  get_it: ^7.6.0
  # Functional programming (Either type)
  dartz: ^0.10.1
  share_plus: ^11.0.0
  flutter_colorpicker: ^1.1.0
  # File caching
  flutter_cache_manager: ^3.3.1
  uuid: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  logger: ^2.0.0

  ffi: any
  network_info_plus: ^6.1.4
  url_launcher: ^6.3.1
  open_filex: ^4.3.4
  gal: ^2.3.0
  # Removed smb_connect - using mobile_smb_native instead
  mobile_smb_native:
    path: ../mobile_smb_native # Local path to mobile SMB plugin
  image: ^4.5.4
  vector_math: ^2.1.4
  pdfx: ^2.0.0
  # HTTP server for streaming files from SMB
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  mime: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  objectbox_generator: ^4.2.0

# Ghi đè các phiên bản gói phụ thuộc để giải quyết xung đột
dependency_overrides:
  intl: ^0.20.2
  pointycastle: ^4.0.0
  # Ensure crypto package is compatible with both FTP and SMB
  crypto: ^3.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
